# Generated by Django 5.2.1 on 2025-05-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0002_remove_expense_name_expense_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
